package:
  name: guessadapt
  version: '0.1'

source:
  git_rev: v0.1
  git_url: git@github.com:micknudsen/guessadapt.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - biopython
    - python >=3.5
