package:
  name: guessadapt
  version: '0.1'

source:
  git_rev: v0.1
  git_url: git@github.com:micknudsen/guessadapt.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

about:
  home: https://github.com/micknudsen/guessadapt
  license: MIT
  summary: Guess which adapter was used in an NGS run
