package:
  name: guessadapt
  version: '0.1_alpha.1'

source:
  git_rev: v0.1-alpha.1
  git_url: git@github.com:micknudsen/guessadapt.git

build:
  number: 0

requirements:
  build:
    - biopython
    - python >=3.6
    - setuptools
  run:
    - biopython
    - python >=3.6
